server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Serve arquivos estáticos normalmente
    location /static/ {
        expires 1y;
        add_header Cache-Control "public";
    }

    # Todas as outras rotas caem no index.html
    location / {
        try_files $uri /index.html;
    }
}